# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusyAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('timeblock', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'busy_at',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'friends',
            },
        ),
        migrations.CreateModel(
            name='OpenAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('open_time', models.IntegerField(blank=True, null=True)),
                ('close_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'open_at',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('allow_strangers', models.BooleanField()),
                ('has_meal_plan', models.BooleanField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='SoldBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=30)),
                ('restaurantid', models.ForeignKey(db_column='restaurantid', on_delete=django.db.models.deletion.DO_NOTHING, to='matchingApp.Restaurant')),
            ],
            options={
                'db_table': 'sold_by',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='matchingApp.Person')),
                ('food_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='openat',
            name='restaurantid',
            field=models.ForeignKey(db_column='restaurantid', on_delete=django.db.models.deletion.DO_NOTHING, to='matchingApp.Restaurant'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to='matchingApp.Person', unique=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to='matchingApp.Person', unique=True),
        ),
        migrations.AddField(
            model_name='busyat',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='matchingApp.Person', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='soldby',
            unique_together=set([('restaurantid', 'food_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='openat',
            unique_together=set([('restaurantid', 'weekday', 'open_time', 'close_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([('user1', 'user2')]),
        ),
        migrations.AlterUniqueTogether(
            name='busyat',
            unique_together=set([('userid', 'weekday', 'timeblock')]),
        ),
    ]
