# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingApp', '0002_buildings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busyat',
            name='timeblock',
            field=models.TimeField(),
        ),
    ]
