# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingApp', '0004_auto_20170414_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likes',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='matchingApp.Person'),
        ),
    ]
