# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingApp', '0005_auto_20170416_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busyat',
            name='weekday',
            field=models.CharField(max_length=5),
        ),
    ]
